### PR TITLE
converted ninjascript to javascript

### PR DESCRIPTION
**Pull request by solderjs**
shoulda just used coffeescript

### CODE REVIEW

**Comment by coolaj86** [comment]
we needs tests for this stuff

**Comment by coolaj86** [comment]
Either the previous commit or mine broke stuff.

**Comment by ryanburnette** [comment]
You need a "horse AJ" Github account.

**Comment by Rob-pw** [comment]
I'll check the committed code this evening to ensure it's all working as expected, having just scanned over it briefly I can't see anything immediately glaring.

**Comment by coolaj86** [comment]
I should post my simple test case file. It failed.


So either I broke something or the prior code broke something.


—

**Comment by Rob-pw** [comment]
You're missing type checking, ```Object.keys``` throws an exception if the parameter is null or undefined.

**Pull request closed without merging**
