### PR TITLE
A small update

### PR DESCRIPTION
**Pull request by Rob-pw**
Todo: Update readme

@ryanburnette Usage is roughly the same, except it now supports nested complex objects, compatible with Asp.net binding.

var qurl = new Qurl();
qurl.query(); // {}
qurl.query('foo'); // undefined

Setting params
qurl.query('foo', 'bar');
qurl.query('array', [1,2,3]);
qurl.query('nested', [1, 2, {
  chums : [{
    name: 'bob',
    age: 27
  }]
});
qurl.query('jeff', false);

qurl.query('jeff'); // false (as Boolean)
qurl.query('nested') // returns the object
qurl.query(); //returns an object of all params

qurl.remove('jeff');
qurl.removeAll();

It'd be nice to get some unit tests for this, although I don't currently have the time to get those written up.

### CODE REVIEW

**Comment by ryanburnette** [comment]
Awesome thanks for the work on enhancements! Testing would be great and
it's something I've been planning to do with my next patch.

**Comment by Rob-pw** [comment]
Glad you like it. Sweet, the API should be quite simple to test, but as it stands I have manually tested all implemented functionality and all use cases I can think of, it's more for future development.

**Comment by ryanburnette** [comment]
I've got it on my to-do list to test everything you added today.

**Comment by Rob-pw** [comment]
I'll update the readme tomorrow morning

**Comment by jbrooksuk** [comment]
@Rob-pw will this be done soon? I can only use Qurl if I'm able to pass an object of parameters :)

**Comment by jbrooksuk** [comment]
Alternatively I'd like to pass a serialized form array through and have all the parameters set that way :)

**Comment by Rob-pw** [comment]
@jbrooksuk - Only the readme is left to update at this point, will likely do this during lunch today. You can pass an object and set parameters as follows:

```javascript
var qurl = new Qurl();
qurl.query({
  myObj : [1,2, {
    withProps: true
  }]
}); //An optional third parameter (true) can be passed if you wish to override any params currently set
```

'pass a serialized form array' - Could you give an example usage?

**Comment by ryanburnette** [comment]
I'm going to tinker on this a bit this morning.

**Comment by Rob-pw** [comment]
Is everything good to merge the PR? Is anything required on my end?

**Comment by ryanburnette** [comment]
@Rob-pw Man this has been forever since I looked at this project. Are you still using any of this code?

**Comment by Rob-pw** [comment]
@ryanburnette Indeed. Not at the moment, though perhaps at some point, what are you proposing? I haven't researched alternatives, but I can imagine Qurl being used where independent modules each control a segment of query params.

**Comment by ryanburnette** [comment]
@Rob-pw Only took me until 2020 to merge it. Might actually use this one day soon.

**Pull request merged**
